### ISSUE TITLE
Not sure if its a bit issue or not

### ISSUE THREAD

**Issue by RaspberryKitty1** [MulverineX/rich-embeds#2]
this plugin seems to just spam the console with errors
![image](https://user-images.githubusercontent.com/28585042/125548585-701cb8a9-bd6a-4c30-9466-69741a4bb2d8.png)

**Comment by MulverineX** [comment]
This plugin is not released. For released plugins check the plugin-links channel on the Powercord Discord server or the powercord-community github [organization](https://github.com/powercord-community).

**Comment by RaspberryKitty1** [comment]
ah ok
